# 生产环境 Docker Compose 配置文件
version: '3.8'

services:
  susheng-ai-app:
    image: 172.27.224.1:5001/susheng-ai-demo:pro
    container_name: susheng-ai-app
    ports:
      - "8080:8000"  # 将主机的 8080 端口映射到容器的 8000 端口
    volumes:
      - ./logs:/app/logs  # 挂载本地 logs 目录到容器内 /app/logs，实现日志持久化
    environment:
      - MYSQL_HOST=${MYSQL_HOST:-172.27.224.1}
      - MYSQL_PORT=${MYSQL_PORT:-3306}
      - MYSQL_USERNAME=${MYSQL_USERNAME:-root}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD:-}
      - MYSQL_DATABASE=${MYSQL_DATABASE:-chat_xz}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - OPENAI_API_BASE=${OPENAI_API_BASE:-https://api.openai.com/v1}
      - OPENAI_API_MODEL=${OPENAI_API_MODEL:-gpt-4o}
      - QUICK_API_KEY=${QUICK_API_KEY}
      - QUICK_API_BASE=${QUICK_API_BASE}
      - QUICK_API_MODEL=${QUICK_API_MODEL:-gpt-4o}
    restart: unless-stopped  # 容器异常退出时自动重启，除非手动停止
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/index"]  # 健康检查命令，访问接口判断服务是否存活
      interval: 30s  # 每 30 秒检查一次
      timeout: 10s   # 检查超时时间为 10 秒
      retries: 3     # 连续失败 3 次视为不健康
